# Site settings
title: Mi pagina pro
email: 
description: > # this means to ignore newlines until "baseurl:"
  Probando jekyll con paginas de github.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: xr900geopelia
github_username:  geopelia

# Build settings
markdown: kramdown
